-- 코드를 입력하세요
SELECT B.CAR_ID FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
ON A.CAR_ID = B.CAR_ID 
WHERE A.CAR_TYPE = "세단" 
AND MONTH(B.START_DATE) = 10
GROUP BY CAR_ID
ORDER BY B.CAR_ID DESC 